//Learta
import java.io.IOException;

public class Item {
	private String itemName;
	private String itemDescription;
	// 0 = Ends after fixed time passes, 1 = Ends after X seconds have passed without bid
	private int closeAuctionType;
	private int startingPrice;
	// Time given for closeAuctionType
	private int time;
	// ID generated by the auction class, which calls the constructor of this class
	private int auctionid;

	public Item() {
	}

	public Item(String itemName, String itemDescription, String closeAuctionType, String startingPrice, String time,
			int auctionid) {
		this.itemName = itemName;
		this.itemDescription = itemDescription;
		try {
			this.closeAuctionType = Integer.parseInt(closeAuctionType);
			this.startingPrice = Integer.parseInt(startingPrice);
			this.time = Integer.parseInt(time);
		} catch (NumberFormatException e) {
			System.out.println(e);
		}
		this.auctionid = auctionid;
	}

	public String getItemName() {
		return itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public String getItemDescription() {
		return itemDescription;
	}

	public void setItemDescription(String itemDescription) {
		this.itemDescription = itemDescription;
	}

	public int getCloseAuctionType() {
		return closeAuctionType;
	}

	public void setCloseAuctionType(int closeAuctionType) {
		this.closeAuctionType = closeAuctionType;
	}

	public int getStartingPrice() {
		return startingPrice;
	}

	public void setStartingPrice(int startingPrice) {
		this.startingPrice = startingPrice;
	}

	public int getTime() {
		return time;
	}

	public void setTime(int time) {
		this.time = time;
	}

	public int getAuctionid() {
		return auctionid;
	}

	public void setAuctionid(int auctionid) {
		this.auctionid = auctionid;
	}

	public String toString() {
		return "ID: " + auctionid + " Item: " + itemName + ", Description: " + itemDescription + ", Starting Price: " + startingPrice + ", Time: " + time + " seconds";
	}
}